Repository Graph-Learning-Benchmarks/gli, pull requests merged in 2023-11, with the labels that each got.

#466 Refactor gli.io
  .github/workflows/pylint.yml
  Makefile
  gli/io.py
  gli/io/__init__.py
  gli/io/edge_task.py
  gli/io/graph.py
  gli/io/graph_task.py
  gli/io/kg_task.py
  gli/io/node_task.py
  gli/io/utils.py
Labels: Refactor

#465 Deprecate outdated doc, templates, and auxiliary files.
  CONTRIBUTING.md
  DATASET_SUBMISSION.md
  FORMAT.md
  datasets/FB13/urls.json
  datasets/FB15K/urls.json
  datasets/FB15K237/urls.json
  datasets/KGMicrobe/urls.json
  datasets/NELL-995/urls.json
  datasets/WN11/urls.json
  datasets/WN18/urls.json
  datasets/WN18RR/urls.json
  datasets/YAGO3-10/urls.json
  datasets/actor/urls.json
  datasets/arxiv-year/metadata.json
  datasets/arxiv-year/urls.json
  datasets/chameleon/urls.json
  datasets/cifar/urls.json
  datasets/citeseer/urls.json
  datasets/cornell/urls.json
  datasets/genius/urls.json
  datasets/mnist/urls.json
  datasets/ogbg-molbace/urls.json
  datasets/ogbg-molclintox/urls.json
  datasets/ogbg-molfreesolv/urls.json
  datasets/ogbg-molhiv/urls.json
  datasets/ogbg-molmuv/urls.json
  datasets/ogbg-molpcba/urls.json
  datasets/ogbg-molsider/urls.json
  datasets/ogbl-collab/urls.json
  datasets/ogbn-arxiv/urls.json
  datasets/ogbn-mag/urls.json
  datasets/ogbn-products/urls.json
  datasets/ogbn-proteins/urls.json
  datasets/penn94/urls.json
  datasets/pokec/urls.json
  datasets/pubmed/urls.json
  datasets/snap-patents/metadata.json
  datasets/snap-patents/urls.json
  datasets/squirrel/urls.json
  datasets/texas/urls.json
  datasets/twitch-gamers/metadata.json
  datasets/twitch-gamers/urls.json
  datasets/wiki/urls.json
  datasets/wisconsin/urls.json
  gli/utils.py
  templates/dataset-folder/task_graph_classification.hjson
  templates/dataset-folder/task_graph_regression.hjson
  templates/dataset-folder/task_kg_entity_prediction.hjson
  templates/dataset-folder/task_kg_relation_prediction.hjson
  templates/dataset-folder/task_link_prediction.hjson
  templates/dataset-folder/task_node_classification.hjson
  templates/dataset-folder/task_node_regression.hjson
  templates/dataset-folder/task_time_dependent_link_prediction.hjson
Labels: documentation

#475 Change default int dtype to np.int64 in `gli.io`
  gli/io/edge_task.py
  gli/io/utils.py
Labels: bug

#472 Reddit Dataset Contribution
  datasets/reddit/LICENSE
  datasets/reddit/README.md
  datasets/reddit/metadata.json
  datasets/reddit/reddit.ipynb
  datasets/reddit/task_node_classification_1.json
Labels: dataset
